services:
  mongo:
    image: mongo:6
    container_name: mongo

  demo:
    image: oliversturm/clean-microservices-cqrs-es-demo:1
    depends_on:
      - mongo
    ports:
      - 3000:3000
      - 3001:3001
      - 3003:3003
      - 3005:3005
      - 3006:3006
      - 3010:3010
